language: cpp
sudo: required
compiler:
  - clang
  - gcc

os:
  - linux

branches:
  only:
    - master
    - develop

before_install:
  - cmake .
  - make

script:
  - make install